### ISSUE TITLE
`require Ecto.Query` must appear earlier

### ISSUE THREAD

**Issue by geekoftheweek** [dwyl/phoenix-ecto-append-only-log-example#18]
In **4.3 Update** when `get(id)` is first changed to `get(entry_id)`, the use of `from/2` causes compilation errors unless `Ecto.Query` is required and imported.  This require and import gets added later in **4.4 Get History**, but running into these unexpected error messages was very confusing for me as an Elixir n00b trying to follow along.

**Comment by mischa-s** [comment]
Ran into this today. To clarify the compile error is `cannot use ^entry_id outside of match clauses` on 4.3, solution is 

/append_only_log.ex
```defmodule Append.AppendOnlyLog do
  alias Append.Repo
  require Ecto.Query
...
  defmacro __before_compile__(_env) do
    quote do
      import Ecto.Query
...```

**Comment by bmartin2015** [comment]
This issue was resolved in https://github.com/dwyl/phoenix-ecto-append-only-log-example/pull/24

**Comment by nelsonic** [comment]
@bmartin2015 thanks again for the PR! 🎉 
(_closing this issue. if still required, please re-open with comment_) 👍
