### ISSUE TITLE
`get_history` does not return an {:ok, _} tuple.

### ISSUE THREAD

**Issue by geekoftheweek** [dwyl/phoenix-ecto-append-only-log-example#19]
The `"get history of item"` test contains this code:
```{:ok, history} = Address.get_history(updated_item)```
but get_history returns `[Ecto.schema.t()] | no_return()`

**Comment by bmartin2015** [comment]
This issue was resolved in https://github.com/dwyl/phoenix-ecto-append-only-log-example/pull/24

**Comment by nelsonic** [comment]
@bmartin2015 thanks again for fixing. ⭐️
