### ISSUE TITLE
ERROR 42P07 (duplicate_table) relation "addresses" already exists

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-ecto-append-only-log-example#25]
While attempting to run the tests on `localhost` I got the following error:
![image](https://user-images.githubusercontent.com/194400/56575954-0cd5ae00-65bf-11e9-9d83-4245cc2ab362.png)

```sh
Generated append app
[debug] QUERY OK source="schema_migrations" db=2.8ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 FOR UPDATE []
[info] == Running 20180912142549 Append.Repo.Migrations.CreateAddresses.change/0 forward
[info] create table addresses
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "addresses" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:595: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute_ddl/4
```

Someone who has only _just_ cloned the repo and installed the deps is unlikely to see this error because they won't have a _duplicate_ project in the same namespace the way I do ...
https://github.com/nelsonic/append-only-log-ex

I need to `DROP` the database and re-create it.

**Comment by nelsonic** [comment]
Run the following commands in your terminal:
```sh
psql -U postgres -c 'DROP DATABASE IF EXISTS append_dev;'
psql -U postgres -c 'DROP DATABASE IF EXISTS append_test;'
mix ecto.create
mix test
MIX_ENV=test mix cover
```

You should see:
![image](https://user-images.githubusercontent.com/194400/56576361-0b58b580-65c0-11e9-8d51-3fbb27b517e6.png)

i.e. tests pass.
(_I was making sure everything was working on `localhost` before tackling #17 ..._ 😉)

**Comment by nelsonic** [comment]
A year later, I'm seeing the same error in a different project and I'm grateful to my past self for creating this issue with the _solution_. (_first result on Google in incognito_) 😻 
In Phoenix `1.5.1` it's just:

```
psql -U postgres -c 'DROP DATABASE IF EXISTS app_dev;'
psql -U postgres -c 'DROP DATABASE IF EXISTS app_test;'
mix test
```

Because now the `mix test` includes:
```
test: ["ecto.create --quiet", "ecto.migrate", "test"]
```

**Comment by jbosse** [comment]
I'm grateful to your past self for creating this issue, too, @nelsonic

**Comment by nelsonic** [comment]
@jbosse stoked you found it helpful. 🎉

**Comment by dani-sanomads** [comment]
but right now in development this is working for me :)
npm i @shopify/shopify-app-session-storage-postgresql@1.0.0-rc.0
